spring:
  application:
    name: ms-books-catalogue
server:
    port: 8082
opensearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  credentials:
    user: ${ELASTICSEARCH_USERNAME:admin}
    password: ${ELASTICSEARCH_PASSWORD:admin}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: buscador.railway.internal

